### ISSUE TITLE
Fail to compile on Ubuntu, GCC 7.3

### ISSUE THREAD

**Issue by PetiteViking** [inviwo/inviwo#106]
When compiling using GCC 7.3.0 on Ubuntu 18.04 I get the following error:
```"GLM_GTX_hash requires C++11 standard library support"```

```
In file included from /home/jochen/git-source/inviwo/include/inviwo/core/util/glm.h:69:0,
                 from /home/jochen/git-source/inviwo/include/inviwo/core/common/inviwo.h:65,
                 from /home/jochen/git-source/inviwo/include/inviwo/core/common/inviwomodule.h:33,
                 from /home/jochen/git-source/inviwo/include/inviwo/core/common/inviwocore.h:34,
                 from /home/jochen/git-source/inviwo/src/core/common/inviwocore.cpp:30:
                 /home/jochen/git-source/inviwo/ext/glm/gtx/hash.hpp:38:3: error: #error "GLM_GTX_hash requires C++11 standard library support"
```

**Comment by petersteneteg** [comment]
is GCC 7.3.0 to new for our glm?

**Comment by petersteneteg** [comment]
@JochenJankowai let me know if you have time maybe we can have a look on this...

**Comment by JochenJankowai** [comment]
I'd assume that GCC 7.3 is too new, GCC 5 and 6 work fine.
