### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by tirpidz** [inviwo/inviwo#545]
Here found another issue on master on (64f9e6f27):
```
[ 39%] Building CXX object modules/core/CMakeFiles/inviwo-core.dir/io/serialization/nodedebugger.cpp.o
In file included from /home/martin/src/inviwo/include/inviwo/core/util/exception.h:35,
                 from /home/martin/src/inviwo/include/inviwo/core/io/serialization/serializationexception.h:35,
                 from /home/martin/src/inviwo/include/inviwo/core/io/serialization/serializebase.h:36,
                 from /home/martin/src/inviwo/include/inviwo/core/io/serialization/deserializer.h:33,
                 from /home/martin/src/inviwo/src/core/io/serialization/deserializer.cpp:30:
/home/martin/src/inviwo/include/inviwo/core/util/sourcecontext.h: In function ‘constexpr bool inviwo::operator==(const inviwo::SourceLocation&, const inviwo::SourceLocation&)’:
/home/martin/src/inviwo/include/inviwo/core/util/sourcecontext.h:155:47: error: ‘strcmp’ is not a member of ‘std’
     return a.getLine() == b.getLine() && std::strcmp(a.getFile(), b.getFile()) == 0 &&
                                               ^~~~~~
/home/martin/src/inviwo/include/inviwo/core/util/sourcecontext.h:155:47: note: suggested alternative:
In file included from /home/martin/src/inviwo/ext/ticpp/tinyxml.h:44,
                 from /home/martin/src/inviwo/ext/ticpp/ticpp.h:56,
                 from /home/martin/src/inviwo/include/inviwo/core/io/serialization/ticpp.h:39,
                 from /home/martin/src/inviwo/include/inviwo/core/io/serialization/serializebase.h:33,
                 from /home/martin/src/inviwo/include/inviwo/core/io/serialization/deserializer.h:33,
                 from /home/martin/src/inviwo/src/core/io/serialization/deserializer.cpp:30:
/usr/include/string.h:136:12: note:   ‘strcmp’
 extern int strcmp (const char *__s1, const char *__s2)
            ^~~~~~
In file included from /home/martin/src/inviwo/include/inviwo/core/util/exception.h:35,
                 from /home/martin/src/inviwo/include/inviwo/core/io/serialization/serializationexception.h:35,
                 from /home/martin/src/inviwo/include/inviwo/core/io/serialization/serializebase.h:36,
                 from /home/martin/src/inviwo/include/inviwo/core/io/serialization/deserializer.h:33,
                 from /home/martin/src/inviwo/src/core/io/serialization/deserializer.cpp:30:
/home/martin/src/inviwo/include/inviwo/core/util/sourcecontext.h:156:17: error: ‘strcmp’ is not a member of ‘std’
            std::strcmp(a.getFunction(), b.getFunction()) == 0;
                 ^~~~~~
/home/martin/src/inviwo/include/inviwo/core/util/sourcecontext.h:156:17: note: suggested alternative:
In file included from /home/martin/src/inviwo/ext/ticpp/tinyxml.h:44,
                 from /home/martin/src/inviwo/ext/ticpp/ticpp.h:56,
                 from /home/martin/src/inviwo/include/inviwo/core/io/serialization/ticpp.h:39,
                 from /home/martin/src/inviwo/include/inviwo/core/io/serialization/serializebase.h:33,
                 from /home/martin/src/inviwo/include/inviwo/core/io/serialization/deserializer.h:33,
                 from /home/martin/src/inviwo/src/core/io/serialization/deserializer.cpp:30:
/usr/include/string.h:136:12: note:   ‘strcmp’
 extern int strcmp (const char *__s1, const char *__s2)
            ^~~~~~
[ 39%] Building CXX object modules/assimp/ext/assimp/assimp/code/CMakeFiles/assimp.dir/Q3BSPZipArchive.cpp.o
[ 39%] Building CXX object modules/core/CMakeFiles/inviwo-core.dir/io/serialization/serializationexception.cpp.o
[ 39%] Building CXX object modules/assimp/ext/assimp/assimp/code/CMakeFiles/assimp.dir/RawLoader.cpp.o
[ 39%] Building CXX object modules/assimp/ext/assimp/assimp/code/CMakeFiles/assimp.dir/SIBImporter.cpp.o
[ 39%] Building CXX object modules/assimp/ext/assimp/assimp/code/CMakeFiles/assimp.dir/SMDLoader.cpp.o
In file included from /home/martin/src/inviwo/include/inviwo/core/util/exception.h:35,
                 from /home/martin/src/inviwo/include/inviwo/core/io/serialization/serializationexception.h:35,
                 from /home/martin/src/inviwo/src/core/io/serialization/serializationexception.cpp:30:
/home/martin/src/inviwo/include/inviwo/core/util/sourcecontext.h: In function ‘constexpr bool inviwo::operator==(const inviwo::SourceLocation&, const inviwo::SourceLocation&)’:
/home/martin/src/inviwo/include/inviwo/core/util/sourcecontext.h:155:47: error: ‘strcmp’ is not a member of ‘std’
     return a.getLine() == b.getLine() && std::strcmp(a.getFile(), b.getFile()) == 0 &&
                                               ^~~~~~
/home/martin/src/inviwo/include/inviwo/core/util/sourcecontext.h:155:47: note: suggested alternative:
In file included from /home/martin/src/inviwo/ext/ticpp/tinyxml.h:44,
                 from /home/martin/src/inviwo/ext/ticpp/ticpp.h:56,
                 from /home/martin/src/inviwo/include/inviwo/core/io/serialization/ticpp.h:39,
                 from /home/martin/src/inviwo/include/inviwo/core/io/serialization/serializationexception.h:34,
                 from /home/martin/src/inviwo/src/core/io/serialization/serializationexception.cpp:30:
/usr/include/string.h:136:12: note:   ‘strcmp’
 extern int strcmp (const char *__s1, const char *__s2)
            ^~~~~~
In file included from /home/martin/src/inviwo/include/inviwo/core/util/exception.h:35,
                 from /home/martin/src/inviwo/include/inviwo/core/io/serialization/serializationexception.h:35,
                 from /home/martin/src/inviwo/src/core/io/serialization/serializationexception.cpp:30:
/home/martin/src/inviwo/include/inviwo/core/util/sourcecontext.h:156:17: error: ‘strcmp’ is not a member of ‘std’
            std::strcmp(a.getFunction(), b.getFunction()) == 0;
                 ^~~~~~
/home/martin/src/inviwo/include/inviwo/core/util/sourcecontext.h:156:17: note: suggested alternative:
In file included from /home/martin/src/inviwo/ext/ticpp/tinyxml.h:44,
                 from /home/martin/src/inviwo/ext/ticpp/ticpp.h:56,
                 from /home/martin/src/inviwo/include/inviwo/core/io/serialization/ticpp.h:39,
                 from /home/martin/src/inviwo/include/inviwo/core/io/serialization/serializationexception.h:34,
                 from /home/martin/src/inviwo/src/core/io/serialization/serializationexception.cpp:30:
/usr/include/string.h:136:12: note:   ‘strcmp’
 extern int strcmp (const char *__s1, const char *__s2)
            ^~~~~~
make[2]: *** [modules/core/CMakeFiles/inviwo-core.dir/build.make:1116: modules/core/CMakeFiles/inviwo-core.dir/io/serialization/serializationexception.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by petersteneteg** [comment]
Should work now, I was able to build with gcc 8.3 at least..
