### ISSUE TITLE
[BUG]: Inviwo does not compile with VS 17.6

### ISSUE THREAD

**Issue by martinfalk** [inviwo/inviwo#1429]
### Problem description

There is a compiler regression bug with the VS C++ compiler in 17.6.x, which prevents compiling Inviwo due to a parameter pack in [`typedmesh.h`](https://github.com/inviwo/inviwo/blob/master/include/inviwo/core/datastructures/geometry/typedmesh.h).

```
inviwo/core/datastructures/geometry/typedmesh.h(342,58): error C3546: '...': there are no parameter packs available to expand (compiling source file src\core\datastructures\geometry\basicmesh.cpp)
inviwo/core/datastructures/geometry/typedmesh.h(518,2): message : see reference to class template instantiation 'inviwo::TypedMesh<BufferTraits...>' being compiled (compiling source file src\core\datastructures\geometry\basicmesh.cpp)
```

See https://developercommunity.visualstudio.com/t/Regression-176:-parameter-pack-expansio/10372131 and 
https://developercommunity.visualstudio.com/t/Compiler-regression-bug-with-VS-2022-v/10392618

### Inviwo version
latest master

### Operating system?
Windows

### Compiler / Version
MSVC 2022 17.6.2, 17.6.3, 17.6.4, 17.6.5

**Comment by petersteneteg** [comment]
Add to the build instructions...

**Comment by martinfalk** [comment]
Added a note to https://github.com/inviwo/inviwo.github.io/blob/master/pages/manual/manual-gettingstarted-build.md

**Comment by petersteneteg** [comment]
It now works in 17.7.0 updated the manual.
